### ISSUE TITLE
Adding support for multiple concurrent progress bars

### ISSUE THREAD

**Issue by samayala22** [mrunderline/cli-progressbar#1]
First of all, your progress bar is awesome! In my case, it works better than tqdm.

I'm working on a multithreaded script that runs a complex function in parallel. In this function, I have a single for loop that iterates over different datasets. When I add your progress bar to this loop, I'd like to be able to **see multiple independent bars that track the progress of the loop in each instance of the function**. For example, if I have 2 datasets, I will start 2 threads with my function, so I should be able to see 2 independent progress bars. Right now, when I run the script, the 2 bars are overlapping until one of the function instances is done processing the data.

Here's a code demo to show what I mean:

```
import time
import threading
import numpy as np
from cli_progressbar import Progress

# Create main dataset with 2 arrays
dataset=[np.random.randint(1,1000,500),np.random.randint(1,2000,750)]

# Printing random text
def foo1(number):
    print('Lorem Ipsum ' + str(number),flush=True)
    time.sleep(1)

# Function that goes through an array of the main dataset
def foo2(num):
    data = dataset[num-1]
    progressbar = Progress()
    progressbar.start('start status' + str(num))
    k=0
    for i in progressbar.iterate(data,'status'):
        k += i
        time.sleep(0.01)
    progressbar.stop('DONE')

# Main function to multithread
def foo_main(num):
    foo1(num)
    foo2(num)

# For Windows
if __name__ == '__main__':
    pid = []
    for i in range(1,len(dataset)+1):
        p = threading.Thread(target=foo_main,args=[i])
        p.start()
        pid.append(p)
    
    for p in pid:
        p.join()
    print ('---------------DONE----------------')
```

Cheers!

**Comment by mrunderline** [comment]
Hi @samayala22!
Thanks for using and letting me know your issue. I'm so happy to make someone job's better :)

For this type of problem, I've add `MultiProgressManager` class to handle multiple progress easier. The reason of create a new class for this mode, was to observe the principle of simplicity. So by install new version you can change your codes to something like this:

```python
import time
import threading
import numpy as np
from cli_progressbar import Progress, MultiProgressManager

# Create main dataset with 2 arrays
dataset = [np.random.randint(1, 1000, 500), np.random.randint(1, 2000, 750)]
manager = MultiProgressManager()  # define a manager

# Printing random text
def foo1(number):
    print('Lorem Ipsum ' + str(number), flush=True)
    time.sleep(1)


# Function that goes through an array of the main dataset
def foo2(num):
    data = dataset[num - 1]
    progressbar = Progress()
    manager.append(progressbar)  # let manager, handle progresses bar
    progressbar.start('start status' + str(num))
    k = 0
    for i in progressbar.iterate(data, 'status' + str(num)):
        k += i
        time.sleep(0.01)
    progressbar.stop('DONE')


# Main function to multithread
def foo_main(num):
    foo1(num)
    foo2(num)


# For Windows
if __name__ == '__main__':
    pid = []
    for i in range(1, len(dataset) + 1):
        p = threading.Thread(target=foo_main, args=[i])
        p.start()
        pid.append(p)
    
    for p in pid:
        p.join()
    print('---------------DONE----------------')
```

**Comment by samayala22** [comment]
Hey @mrunderline !

Thanks for handling the suggestion. Just a quick heads up, there's an error when upgrading the package via `pip`:

```
ERROR: Command errored out with exit status 1:
     command: 'c:\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\samay\\AppData\\Local\\Temp\\pip-install-j5515s4b\\cli-progressbar_189fe7eb1cc540efbdd1be6dad229cac\\setup.py'"'"'; __file__='"'"'C:\\Users\\samay\\AppData\\Local\\Temp\\pip-install-j5515s4b\\cli-progressbar_189fe7eb1cc540efbdd1be6dad229cac\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\samay\AppData\Local\Temp\pip-pip-egg-info-x89q9l8f'
         cwd: C:\Users\samay\AppData\Local\Temp\pip-install-j5515s4b\cli-progressbar_189fe7eb1cc540efbdd1be6dad229cac\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\samay\AppData\Local\Temp\pip-install-j5515s4b\cli-progressbar_189fe7eb1cc540efbdd1be6dad229cac\setup.py", line 17, in <module>
        long_description=get_long_description(),
      File "C:\Users\samay\AppData\Local\Temp\pip-install-j5515s4b\cli-progressbar_189fe7eb1cc540efbdd1be6dad229cac\setup.py", line 6, in get_long_description
        readme = open("README.rst").read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I tried your new release in my code and it worked well for 2 threads, but if I increased the number of threads and added some text in my `foo2` function, the output quickly begins to get messy.

```
PS C:\Users\samay\Documents\Esports_Highlights\tools> python .\temp.py
Starting thread 0
Starting thread 1
Starting thread 2
Starting thread 3
Starting thread 4
Starting thread 5
Teeeext████--------------------------------------------------] 16.7% | 133/796 | status1
Teeeext████████----------------------------------------------] 23.1% | 184/796 | status1
Teeeext███████████████████████████████████████████████-------] 87.7% | 698/796 | status1
Teeeext████████████████████████████████████████████████████--] 95.9% | 763/796 | status1
Teeeext██████████████████████████████████████████████████████] 100.0% | 796/796 | DONE
[████████████████████████████████████████████████████████████] 100.0% | 751/751 | DONE
[███████████████████████████████████████████████████---------] 85.4% | 685/802 | status3
[████████████████████████████████████████████████████████----] 93.3% | 748/802 | status3
[██████████████████████████████████████████████████████████--] 97.3% | 780/802 | status3
[████████████████████████████████████████████████████████████] 100.0% | 802/802 | DONE

Teeeext
---------------DONE----------------
PS C:\Users\samay\Documents\Esports_Highlights\tools>
```
This was expected because of the very nature of threading which sometimes causes 2 (or more) bars printing at the same time which moves the whole output by 1+ newline.
Before you responded to my issue, I tried some things in your code including using [ANSI escape codes](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797) and thread locking. The result worked perfectly until I decided to add text after the `for ` loop in `foo2`. The text should ideally either replace the bar or be printed right below the corresponding bar. I figured everything could be fixed if I could get the cursor position in the terminal, but unfortunately I didn't find a way to get it. If you find a clever way to solve this, let me know :)

Here's the code I used for the messy output test:

```python
import time
import threading
import numpy as np
from cli_progressbar import Progress, MultiProgressManager

# Create main dataset with as many arrays as threads you wish to use
#==================
num_arr = 6
#==================
dataset = []
for k in range(num_arr):
    dataset.append(np.random.randint(1,1000,np.random.randint(100,1000)))

manager = MultiProgressManager()  # define a manager

# Printing random text
def foo1(number):
    print('Starting thread ' + str(number), flush=True)
    time.sleep(1)


# Function that goes through an array of the main dataset
def foo2(num):
    data = dataset[num]
    progressbar = Progress()
    manager.append(progressbar)  # let manager, handle progresses bar
    progressbar.start('start status' + str(num))
    k = 0
    for i in progressbar.iterate(data, 'status' + str(num)):
        k += i
        time.sleep(0.01)
    progressbar.stop('DONE')
    print('Teeeext')


# Main function to multithread
def foo_main(num):
    foo1(num)
    foo2(num)

# For Windows
if __name__ == '__main__':
    pid = []
    start = time.time()
    total = len(dataset)
    for i in range(total):
        p = threading.Thread(target=foo_main,args=(i,))
        p.start()
        pid.append(p)
    
    for p in pid:
        p.join()
    
    print('---------------DONE----------------')
```
